export const medications = [
  "Aspirin",
  "Ibuprofen",
  "Paracetamol",
  "Acetaminophen",
  "Naproxen",
  "Aleve",
  "Tylenol",
  "Advil",
  "Motrin",
  "Amoxicillin",
  "Azithromycin",
  "Metformin",
  "Furosemide",
  "Atorvastatin",
  "Metoprolol",
  "Hydrochlorothiazide",
  "Esomeprazole",
  "Amlodipine",
  "Omeprazole",
  "Lisinopril",
  "Levothyroxine",
  "Atenolol",
  "Hydrocodone",
  "Alprazolam",
  "Simvastatin",
  "Sertraline",
  "Lorazepam",
  "Citalopram",
  "Ciprofloxacin",
  "Warfarin",
  "Triamterene",
  "Cyclobenzaprine",
  "Fluticasone",
  "Cephalexin",
  "Clonazepam",
  "Escitalopram",
  "Gabapentin",
  "Clopidogrel",
  "Pravastatin",
  "Albuterol",
  "Fluoxetine",
  "Sulfamethoxazole",
  "Trimethoprim",
  "Montelukast",
  "Prednisone",
  "Tramadol",
  "Naproxen",
  "Cetirizine",
  "Carvedilol",
  "Rosuvastatin",
  "Duloxetine",
  "Trazodone",
  "Fluconazole",
  "Valsartan",
  "Venlafaxine",
  "Amitriptyline",
  "Alendronate",
  "Potassium chloride",
  "Lovastatin",
  "Meloxicam",
  "Paroxetine",
  "Diazepam",
  "Doxycycline",
  "Prazosin",
  "Nebivolol",
  "Pioglitazone",
  "Clonidine",
  "Celecoxib",
  "Tamsulosin",
  "Insulin glargine",
  "Levofloxacin",
  "Methylprednisolone",
  "Oxycodone",
  "Promethazine",
  "Lansoprazole",
  "Azilsartan",
  "Quetiapine",
  "Carisoprodol",
  "Fenofibrate",
  "Codeine",
  "Enalapril",
  "Sildenafil",
  "Dexmethylphenidate",
  "Ethinyl estradiol",
  "Allopurinol",
  "Spironolactone",
  "Ramipril",
  "Glimepiride",
  "Methylphenidate",
  "Losartan",
  "Levocetirizine",
  "Folic acid",
  "Isosorbide mononitrate",
  "Digoxin",
  "Pregabalin",
  "Triamcinolone",
  "Desvenlafaxine",
  "Cefdinir",
  "Insulin detemir",
  "Rivaroxaban",
  "Temazepam",
  "Oseltamivir",
  "Valacyclovir",
  "Labetalol",
  "Ezetimibe",
  "Aripiprazole",
  "Amphetamine",
  "Phentermine",
  "Donepezil",
  "Olmesartan",
  "Diclofenac",
  "Lisinopril + HCTZ",
  "Clindamycin",
  "Metronidazole",
  "Glipizide",
  "Lamotrigine",
  "Levothyroxine (Levoxyl)",
  "Gemfibrozil",
  "Benazepril",
  "Ethinyl estradiol + norgestimate",
  "Metoclopramide",
  "Risperidone",
  "Tiotropium",
  "Verapamil",
  "Hydroxyzine",
  "Meclizine",
  "Buspirone",
  "Diltiazem",
  "Doxazosin",
  "Divalproex",
  "Tolterodine",
  "Nitrofurantoin",
  "Losartan + HCTZ",
  "Propranolol",
  "Sitagliptin",
  "Pramipexole",
  "Apixaban",
  "Mirtazapine",
  "Guaifenesin",
  "Buprenorphine",
  "Topiramate",
  "Lisdexamfetamine",
  "Bupropion",
  "Latanoprost",
  "Acyclovir",
  "Quinapril",
  "Rabeprazole",
  "Irbesartan",
  "Mupirocin",
  "Ibandronate",
  "Albuterol + Ipratropium",
  "Fentanyl",
  "Mirabegron",
  "Butalbital",
  "Polyethylene glycol",
  "Terazosin",
  "Sumatriptan",
  "Guanfacine",
  "Carbamazepine",
  "Methimazole",
  "Famotidine",
  "Nifedipine",
  "Finasteride",
  "Methotrexate",
  "Benzonatate",
  "Risedronate",
  "Irbesartan + HCTZ",
  "Dicyclomine",
  "Clarithromycin",
  "Varenicline",
  "Raloxifene",
  "Insulin lispro",
  "Insulin degludec",
  "Memantine",
  "Nitroglycerin",
  "Insulin aspart",
  "Dulaglutide",
  "Nabumetone",
  "Ropinirole",
  "Methocarbamol",
  "Clobetasol",
  "Tizanidine",
  "Bisoprolol",
  "Ondansetron",
  "Olanzapine",
  "Hydralazine",
  "Moxifloxacin",
  "Dutasteride",
  "Triamterene + HCTZ",
  "Benztropine",
  "Adalimumab",
  "Phenytoin",
  "Oxybutynin",
  "Levetiracetam",
  "Liraglutide",
  "Baclofen",
  "Oxcarbazepine",
  "Ketoconazole",
  "Nortriptyline",
  "Hydroxychloroquine",
  "Pantoprazole",
  "Phenazopyridine",
  "Atomoxetine",
  "Metformin + Sitagliptin",
  "Empagliflozin",
  // Add more if needed to reach 200
];
